#!/bin/bash
#SBATCH -A uot187
#SBATCH --job-name="twitter.local"
#SBATCH --output="twitter.local.out"
#SBATCH --partition=shared
#SBATCH --nodes=1
#SBATCH --ntasks-per-node=4
#SBATCH --mem=16G
#SBATCH --export=ALL 
#SBATCH --time=10

module load openjdk
SW=/expanse/lustre/projects/uot187/fegaras
export HADOOP_HOME=$SW/hadoop-3.2.2
PATH="$HADOOP_HOME/bin:$PATH"

rm -rf temp output
hadoop --config $SW/conf jar twitter.jar Twitter small-twitter.csv temp output
